"""recolor_session() against a synthetic closed session."""

from __future__ import annotations

import json
import re
from dataclasses import replace
from pathlib import Path

import numpy as np
import pytest

from streettracker.analysis.recolor import (
    RecolorStats,
    find_color_crop,
    recolor_session,
)
from streettracker.common.output import EventLog, save_data_json
from streettracker.common.schema import TrackRecord
from streettracker.common.summary import generate_html

cv2 = pytest.importorskip("cv2")


def _solid_bgr(h: int, w: int, bgr: tuple[int, int, int]) -> np.ndarray:
    img = np.zeros((h, w, 3), dtype=np.uint8)
    img[:, :, 0] = bgr[0]
    img[:, :, 1] = bgr[1]
    img[:, :, 2] = bgr[2]
    return img


@pytest.fixture
def synthetic_session(tmp_path: Path, sample_track: TrackRecord) -> Path:
    """Build a closed session directory with:
       - events.jsonl + data.json + hourly.json + summary.html
       - vehicle_<id>_hq.jpg crops in actually-distinct colors
       - records whose stored colors are wrong (so recolor has work to do)
    """
    session = tmp_path / "session_test"
    session.mkdir()

    # Three tracks with different *actual* crop colors; their JSON says
    # "unknown" so recolor must change all three.
    track_red = replace(sample_track, track_id=1, color="unknown")
    track_blue = replace(sample_track, track_id=2, color="unknown",
                         time_start_unix=sample_track.time_start_unix + 10)
    track_white = replace(sample_track, track_id=3, color="unknown",
                          time_start_unix=sample_track.time_start_unix + 20)
    tracks = [track_red, track_blue, track_white]

    cv2.imwrite(str(session / "vehicle_1_hq.jpg"),
                _solid_bgr(100, 100, (0, 0, 255)))     # red
    cv2.imwrite(str(session / "vehicle_2_hq.jpg"),
                _solid_bgr(100, 100, (255, 80, 0)))    # blue
    cv2.imwrite(str(session / "vehicle_3_hq.jpg"),
                _solid_bgr(100, 100, (255, 255, 255)))  # white

    # events.jsonl
    with EventLog(session / "test_events.jsonl") as log:
        for t in tracks:
            log.append(t)

    # data.json
    save_data_json(tracks, session / "test_data.json")

    # hourly.json — we don't care about correctness here; just that
    # recolor preserves ir_periods.
    (session / "test_hourly.json").write_text(
        json.dumps({"hours": [], "ir_periods": [{"start": "x", "end": "y", "duration_s": 99.0}]}),
        encoding="utf-8",
    )

    # summary.html — generated by the real summary module so the embedded
    # JSON pattern matches.
    generate_html(
        records=tracks,
        output_dir=session,
        html_path=session / "test_summary.html",
        session_label="test",
        meta={},
        refresh_seconds=0,
    )

    return session


def test_find_color_crop_prefers_vehicle_prefix(tmp_path: Path) -> None:
    crop = tmp_path / "vehicle_42_hq.jpg"
    crop.write_bytes(b"x")
    assert find_color_crop(tmp_path, 42) == crop


def test_find_color_crop_falls_back_to_person_prefix(tmp_path: Path) -> None:
    crop = tmp_path / "person_42_hq.jpg"
    crop.write_bytes(b"x")
    assert find_color_crop(tmp_path, 42) == crop


def test_find_color_crop_returns_none_when_missing(tmp_path: Path) -> None:
    assert find_color_crop(tmp_path, 999) is None


def test_recolor_session_updates_records(synthetic_session: Path) -> None:
    stats = recolor_session(synthetic_session)
    assert isinstance(stats, RecolorStats)
    assert stats.records_total == 3
    assert stats.records_changed == 3   # all started as "unknown"
    assert stats.records_missing_crop == 0
    assert stats.distribution_before == {"unknown": 3}
    assert "red" in stats.distribution_after
    assert "blue" in stats.distribution_after
    assert "white" in stats.distribution_after


def test_recolor_session_rewrites_events_jsonl(synthetic_session: Path) -> None:
    recolor_session(synthetic_session)
    lines = (synthetic_session / "test_events.jsonl").read_text().splitlines()
    parsed = [json.loads(line) for line in lines if line.strip()]
    colors = {r["track_id"]: r["color"] for r in parsed}
    assert colors == {1: "red", 2: "blue", 3: "white"}


def test_recolor_session_rewrites_data_json(synthetic_session: Path) -> None:
    recolor_session(synthetic_session)
    data = json.loads((synthetic_session / "test_data.json").read_text())
    colors = {r["track_id"]: r["color"] for r in data}
    assert colors == {1: "red", 2: "blue", 3: "white"}


def test_recolor_session_preserves_ir_periods(synthetic_session: Path) -> None:
    recolor_session(synthetic_session)
    hourly = json.loads((synthetic_session / "test_hourly.json").read_text())
    assert hourly["ir_periods"] == [{"start": "x", "end": "y", "duration_s": 99.0}]


def test_recolor_session_patches_summary_html(synthetic_session: Path) -> None:
    recolor_session(synthetic_session)
    html = (synthetic_session / "test_summary.html").read_text()
    m = re.search(
        r'<script id="vehicles-data" type="application/json">(.*?)</script>',
        html, re.DOTALL,
    )
    assert m is not None
    embedded = json.loads(m.group(1))
    colors = {r["track_id"]: r["color"] for r in embedded}
    assert colors == {1: "red", 2: "blue", 3: "white"}


def test_recolor_session_missing_crop_keeps_old_color(
    tmp_path: Path, sample_track: TrackRecord
) -> None:
    """If the crop JPEG is gone, the record's old color is retained."""
    session = tmp_path / "s"
    session.mkdir()
    track = replace(sample_track, color="orange")  # not in COLOR_RANGES; will survive
    with EventLog(session / "x_events.jsonl") as log:
        log.append(track)
    stats = recolor_session(session)
    assert stats.records_missing_crop == 1
    assert stats.records_changed == 0
    # The track's color is unchanged
    parsed = json.loads((session / "x_events.jsonl").read_text().strip())
    assert parsed["color"] == "orange"


def test_recolor_session_without_jsonl_raises(tmp_path: Path) -> None:
    with pytest.raises(FileNotFoundError, match="events.jsonl"):
        recolor_session(tmp_path)
